### ISSUE TITLE
Review and address js issues reported by snyk

### ISSUE THREAD

**Issue by jcfr** [girder/girder#1892]
This report is related to current master.

See https://snyk.io/test/github/girder/girder

**Comment by jcfr** [comment]
I looked into the remaining issues related to JQuery, after updating to 3.2.1 and rebuilding .. I get error like the one reported here when running the test listed below.

I suspect the save function called here is the source ... https://github.com/girder/girder/blob/834cf29acc3538b38ba24e6e7203852924110843/clients/web/src/views/layout/RegisterView.js#L17-L74

and I could track the corresponding save method all the way to here: https://github.com/jashkenas/backbone/blob/53f77901a4ea9c7cf75d3db93ddddf491998d90f/backbone.js#L446-L499

And here is the upgrade guide: http://jquery.com/upgrade-guide/3.0/

Any help to address these would be appreciated.

The error:

```
50: ERROR: TypeError: undefined is not a function (near '...}, this)).error(_underscore2.defaul...')
50: TRACE:
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 20766 (in function "save")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 25544 (in function "submitGRegisterForm")
50:  -> : 0 (in function "submitGRegisterForm")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 10112 (in function "dispatch")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 9920 (in function "handle")
50:  -> : 0 (in function "click")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 13141 (in function "trigger")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 13175
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 5268 (in function "each")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 5063 (in function "each")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 13174 (in function "trigger")
50:  -> http://localhost:30001/clients/web/static/built/girder_lib.min.js: 13196
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 2
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 1 (in function "execute")
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 1 (in function "next_")
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 1 (in function "e")
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 2 (in function "execute")
50:  -> http://localhost:30001/static/built/testing/testing.min.js: 2
```

The failing tests:

```
	 50 - web_client_data_filesystem (Failed)
	 51 - web_client_data_gridfs (Failed)
	 52 - web_client_data_gridfsrs (Failed)
	 53 - web_client_data_s3 (Failed)
	 54 - web_client_admin (Failed)
	 55 - web_client_collection (Failed)
	 56 - web_client_collection_base_class (Failed)
	 57 - web_client_group (Failed)
	 58 - web_client_user (Failed)
	 59 - web_client_item (Failed)
	 60 - web_client_folder (Failed)
	 61 - web_client_routing (Failed)
	 63 - web_client_custom_widgets (Failed)
	 64 - web_client_widgets (Failed)
	 66 - web_client_empty_layout (Failed)
	 68 - web_client_browser (Failed)
	 74 - web_client_authorized_upload.authorized_upload (Failed)
	 87 - web_client_provenance.provenance (Failed)
	 97 - web_client_item_licenses.item_licenses (Failed)
	105 - web_client_autojoin.autojoin (Failed)
	109 - web_client_thumbnails.thumbnails (Failed)
	120 - web_client_geospatial.geospatial (Failed)
	146 - web_client_user_quota.user_quota (Failed)
	155 - web_client_jobs.jobs (Failed)
	163 - web_client_curation.curation (Failed)
	167 - web_client_item_tasks.widgets (Failed)
	168 - web_client_item_tasks.tasks (Failed)
	176 - web_client_hashsum_download.hashsum_download (Failed)
```

**Comment by matthewma7** [comment]
@jcfr Is this something http://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin would help us?

**Comment by jcfr** [comment]
Code in girder_lib.min.js is:

```
    save: function save(event, value) {
        event.stopImmediatePropagation();
        var curRow = (0, _jquery2.default)(event.currentTarget.parentElement),
            tempKey = curRow.find('.g-widget-metadata-key-input').val(),
            tempValue = value !== undefined ? value : curRow.find('.g-widget-metadata-value-input').val();

        if (this.newDatum && tempKey === '') {
            _events2.default.trigger('g:alert', {
                text: 'A key is required for all metadata.',
                type: 'warning'
            });
            return;
        }

        var saveCallback = _underscore2.default.bind(function () {
            this.key = tempKey;
            this.value = tempValue;

            this.parentView.key = this.key;
            this.parentView.value = this.value;

            if (this instanceof JsonMetadatumEditWidget) {
                this.parentView.mode = 'json';
            } else {
                this.parentView.mode = 'simple';
            }

            this.parentView.render();

            this.newDatum = false;
        }, this);

        var errorCallback = function errorCallback(out) {
            _events2.default.trigger('g:alert', {
                text: out.message,
                type: 'danger'
            });
        };
```

And it is using the `bind` function ... most likely related to http://jquery.com/upgrade-guide/3.0/#deprecated-bind-and-delegate

Will check to update our backbone js which is from 2014

**Comment by jcfr** [comment]
Digging further, I was incorrect .. issue is in this file: https://github.com/girder/girder/blob/207710c18b7172fac45143a62a21517cf7a814c0/clients/web/src/models/Model.js#L42-L78

In this code snippet:

```js
        return restRequest({
            path: path,
            type: type,
            data: data,
            error: null // don't do default error behavior (validation may fail)
        }).done(_.bind(function (resp) {
            this.set(resp);
            this.trigger('g:saved');
        }, this)).error(_.bind(function (err) {
            this.trigger('g:error', err);
}, this));
```

`.error` evaluates to `undefined`

**Comment by jbeezley** [comment]
This should fix it.
```javascript
.then((resp) => {
    this.set(resp);
    this.trigger('g:saved');
}, (err) => {
    this.trigger('g:error', err);
})
```

**Comment by jcfr** [comment]
Thanks @jbeezley that was it.

**Comment by zachmullen** [comment]
The `done` & `error` chaining occurs throughout the code, this would break a lot of places, including in plugins we don't know about... we'd either need to polyfill it or stay on the current major jquery version.

**Comment by jcfr** [comment]
> chaining occurs throughout the code,

Indeed, using a combination of search/replace magic and manual tweaks, code base has been updated.

I guess we could either add a dependency on `jquery-migrate` or explicitly integrate these:
https://github.com/jquery/jquery-migrate/blob/master/src/deferred.js
https://github.com/jquery/jquery-migrate/blob/master/src/ajax.js

@zachmullen I will let you decide what is best

**Comment by manthey** [comment]
If you don't have a polyfill, we'd have to bump major version, or plugins will all break.

**Comment by jcfr** [comment]
Makes sense. I will add a polyfill.

**Comment by jcfr** [comment]
I tried few things but fail to integrate jquery-migrate. I will fix the remaining warning so that the topic is green and will let someone else take over.

**Comment by jcfr** [comment]
Here are two topics updating jquery.

After addressing the `stopPropagation` issue .. I will make only one topic (Since `jquery-migrate` will be integrated into girder libraries, we should have backward compat)

That said, does any one got an error like the one reported below ... ?



###  update-jquery-to-address-snyk-js-vulnerabilities

This topic updates the entire code base to make use of then, and done/fail

See https://github.com/girder/girder/tree/update-jquery-to-address-snyk-js-vulnerabilities

Test report: https://circleci.com/gh/girder/girder/1006

Failing tests:

```
	 50 - web_client_data_filesystem (Failed)
	 51 - web_client_data_gridfs (Failed)
	 52 - web_client_data_gridfsrs (Failed)
	 53 - web_client_data_s3 (Failed)
	 54 - web_client_admin (Failed)
	 60 - web_client_folder (Failed)
	 63 - web_client_custom_widgets (Failed)
	 68 - web_client_browser (Failed)
	143 - web_client_item_tasks.tasks (Failed)
	173 - web_client_thumbnails.thumbnails (Failed)
```


### update-jquery-to-address-snyk-js-vulnerabilities-with-jqyer-migrate

This topic update the version of Jquery and integrate jquery-migrate

Test report: https://circleci.com/gh/girder/girder/1005

Failing tests:

```
	 50 - web_client_data_filesystem (Failed)
	 51 - web_client_data_gridfs (Failed)
	 52 - web_client_data_gridfsrs (Failed)
	 53 - web_client_data_s3 (Failed)
	 60 - web_client_folder (Failed)
	 68 - web_client_browser (Failed)
	 84 - web_client_autojoin.autojoin (Failed)
	134 - web_client_item_licenses.item_licenses (Failed)
	143 - web_client_item_tasks.tasks (Failed)
	173 - web_client_thumbnails.thumbnails (Failed)
```

### TypeError: undefined is not a constructor

In both case, I get errors like this one:

```
50:  Error: TypeError: undefined is not a constructor (evaluating 'e.stopPropagation()') in http://localhost:30001/clients/web/static/built/girder_lib.min.js (line 11188)
```
